In [1]:
import tensorflow as tf
a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))


/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


[[22. 28.]
 [49. 64.]]


In [2]:
with tf.device('/cpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))


[[22. 28.]
 [49. 64.]]


In [3]:
with tf.device('/gpu:0'):
  a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
  b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(c))

[[22. 28.]
 [49. 64.]]


In [14]:
import sys
import numpy as np
import tensorflow as tf
from datetime import datetime

def matmul(device_name="gpu", shape=(10,10)):
#device_name = sys.argv[1]  # Choose device from cmd line. Options: gpu or cpu
#shape = (int(sys.argv[2]), int(sys.argv[2]))
    if device_name == "gpu0":
        device_name = "/gpu:0"
    elif device_name == "gpu1":
        device_name = "/gpu:1"
    else:
        device_name = "/cpu:0"

    with tf.device(device_name):
        random_matrix = tf.random_uniform(shape=shape, minval=0, maxval=1)
        dot_operation = tf.matmul(random_matrix, tf.transpose(random_matrix))
        sum_operation = tf.reduce_sum(dot_operation)


    startTime = datetime.now()
    with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as session:
            result = session.run(sum_operation)
            print(result)

    # It can be hard to see the results on the terminal with lots of output -- add some newlines to improve readability.
    print("\n" * 5)
    print("Shape:", shape, "Device:", device_name)
    print("Time taken:", datetime.now() - startTime)

    print("\n" * 5)

In [20]:
matmul(device_name="cpu",shape=(10000,10000))


254401050000.0






('Shape:', (10000, 10000), 'Device:', '/cpu:0')
('Time taken:', datetime.timedelta(0, 20, 334651))








In [15]:
matmul(device_name="gpu0",shape=(10000,10000))

250021800000.0






('Shape:', (10000, 10000), 'Device:', '/gpu:0')
('Time taken:', datetime.timedelta(0, 0, 419122))








In [16]:
matmul(device_name="gpu1",shape=(10000,10000))

250002110000.0






('Shape:', (10000, 10000), 'Device:', '/gpu:1')
('Time taken:', datetime.timedelta(0, 0, 907009))








In [19]:
%%bash
nvidia-smi

Tue Feb 20 13:38:53 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 387.26                 Driver Version: 387.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:02:00.0 Off |                  N/A |
| 31%   48C    P8    29W / 250W |   5801MiB /  6080MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:03:00.0 Off |                  N/A |
| 22%   51C    P2    76W / 250W |  11633MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
        